apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nodeapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: devopsedu/employee
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
