apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rsvp
  namespace: testing-jsayar
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rsvp
    spec:
      containers:
      - name: rsvp-app
        image: devopsedu/employee
        env:
        - name: MONGODB_HOST
          value: mongodb
        ports:
        - containerPort: 8888
          name: web-port
