apiVersion: v1
kind: Service
metadata:
  name: rsvp
  namespace: testing-jsayar
  labels:
    apps: rsvp
spec:
  type: NodePort
  ports:
  - name: tcp-31081-8888
    nodePort: 31081
    port: 8888
    protocol: TCP
  selector:
    app: rsvp
