apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  type: LoadBalancer
  ports:
  - name: node-service
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: nodeapp
